In [1]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv('/Users/rahulgarg/github/AnalyticsCourse/datasets/titanic/train.csv')

In [4]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
type(train)

pandas.core.frame.DataFrame

In [6]:
arr = [1, 2, 3]

In [7]:
arr.loc[1]

AttributeError: 'list' object has no attribute 'loc'

In [24]:
train.loc[1 , ['PassengerId','Survived']]

PassengerId    2
Survived       1
Name: 1, dtype: object

In [31]:
df = pd.DataFrame(train.loc[1])

In [32]:
type(df)

pandas.core.frame.DataFrame

In [33]:
df

1
PassengerId                                                  2
Survived                                                     1
Pclass                                                       1
Name         Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                     female
Age                                                         38
SibSp                                                        1
Parch                                                        0
Ticket                                                PC 17599
Fare                                                   71.2833
Cabin                                                      C85
Embarked                                                     C

In [37]:
df

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                           38
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

df.loc

In [12]:
type(train.loc[1])

pandas.core.series.Series

In [14]:
train.loc[1]

array([2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C'],
      dtype=object)

In [10]:
train.Name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [11]:
type(train.Name)

pandas.core.series.Series

# Series 

In [39]:
type(train)

pandas.core.frame.DataFrame

In [48]:
series = train.loc[1]
series


PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                           38
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [44]:
type(series)

pandas.core.series.Series

In [49]:
series.Name

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [50]:
series.index

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [52]:
series.name

1

In [56]:
df = pd.DataFrame(train.loc[1])
df

1
PassengerId                                                  2
Survived                                                     1
Pclass                                                       1
Name         Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                     female
Age                                                         38
SibSp                                                        1
Parch                                                        0
Ticket                                                PC 17599
Fare                                                   71.2833
Cabin                                                      C85
Embarked                                                     C

In [57]:
type(df)

pandas.core.frame.DataFrame

In [63]:
df.loc['Name',1]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

# NUMPY

In [64]:
my_list = [1,2,3]

In [66]:
for i in my_list:
    print(i*2)

2
4
6


In [78]:
my_arr1 = np.array([1,2,3])

In [79]:
my_arr1

array([1, 2, 3])

In [80]:
my_arr1*2

array([2, 4, 6])

In [81]:
type(my_arr1)

numpy.ndarray

In [82]:
my_arr2 = np.array([[1,2,3],[4,5,6]])

In [83]:
my_arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
my_arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
type(my_arr2)

numpy.ndarray

In [90]:
my_arr1

array([1, 2, 3])

In [104]:
my_arr = my_arr2*my_arr1

In [105]:
my_arr

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [106]:
my_arr.shape

(2, 3)

In [112]:
my_arr[1,2] = 20.20

In [113]:
my_arr

array([[ 1,  4,  9],
       [ 4, 10, 20]])

In [118]:
my_arr = np.array([[ 1.1,  4.4,  9.9],[ 4, 10, 20.2]])

In [119]:
my_arr

array([[ 1.1,  4.4,  9.9],
       [ 4. , 10. , 20.2]])

In [120]:
my_arr.dtype

dtype('float64')

In [95]:
df = pd.DataFrame(my_arr2*my_arr1, columns = ['a','b', 'c'], index =['first','second'])

In [96]:
df.shape

(2, 3)

In [102]:
df.dtypes

a    int64
b    int64
c    int64
dtype: object

In [127]:
my_arr = np.array([1.1,  4.4,  9.9])

In [128]:
my_arr

array([1.1, 4.4, 9.9])

In [136]:
lst = [1,2,3]

In [131]:
np.array(lst)

array([1, 2, 3])

In [137]:
tupl = 5, 6,7,8

In [138]:
tupl

(5, 6, 7, 8)

In [142]:
np.array([[1,2,3], tupl])

array([[1, 2, 3, 5],
       [5, 6, 7, 8]])

In [145]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [146]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [147]:
range(0,10,2)

range(0, 10, 2)

In [150]:
range(0,10,2)

range(0, 10, 2)


In [153]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])